volumes:
  tmp: ~

services:
  php:
    build: .
    environment:
      - OPENAI_API_KEY
      - PHP_EXTENSION_INTL=1
    volumes:
      - .:/usr/src/app:cached

      # persist cache
      - tmp:/tmp
